### PR TITLE
Replace time with std::time

### PR DESCRIPTION
**Pull request by serprex**

### CODE REVIEW

**Comment by est31** [comment]
Something is wrong. Output before: `speed: 8.864134 kb per ms`. Output after: `speed: 8639153.172553392 kb per ms`

**Comment by serprex** [comment]
Whoops, need to divide seconds by 1000, not multiply

**Comment by est31** [comment]
Still wrong. I'll merge it then fix it myself.

**Comment by serprex** [comment]
Oh, you were having ns as the f32 & then multiplying by 1000 to offset the extra 1000 in the ms counter

Sorry for my confusion

**Pull request merged**
